---
- name: configure servers with nginx
  hosts: webservers
  sudo: True
  vars:
    conf_file: /etc/nginx/sites-available/default
  tasks:
    - name: Install nginx
      apt: name=nginx update_cache=yes
    
    - name: copy nginx config file
      copy: src=files/nginx.conf dest={{ conf_file }}
    
    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link
      notify: restart nginx
    
    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html
        mode=0644
      notify: restart nginx
  
  handlers:
    - name: restart nginx
      apt: name=nginx update_cache=yes